# 'version' sudah tidak diperlukan lagi, jadi kita hapus
services:
  database:
    image: mariadb:10.11
    container_name: pterodactyl_database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'bgsgtg' # Ganti dengan password root yang kuat
      MYSQL_DATABASE: 'panel'
      MYSQL_USER: 'pterodactyl'
      MYSQL_PASSWORD: 'bgsgtg' # Ganti dengan password user yang kuat
    networks:
      - pterodactyl_network

  cache:
    image: redis:7.0-alpine
    container_name: pterodactyl_cache
    restart: always
    networks:
      - pterodactyl_network

  panel:
    # --- PERUBAHAN DI SINI ---
    # Menggunakan image tag yang lebih baru dan valid
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl_panel
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - database
      - cache
    volumes:
      - ./data/panel:/var/www/html
      - ./data/nginx:/etc/nginx/sites-enabled
    environment:
      APP_URL: 'http://127.0.0.1:8080'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'panel'
      DB_USERNAME: 'pterodactyl'
      DB_PASSWORD: 'bgsgtg' # Gunakan password yang sama dengan di 'database'
      REDIS_HOST: 'cache'
      REDIS_PORT: '6379'
      PHP_MEMORY_LIMIT: '512M'
      PHP_UPLOAD_MAX_FILESIZE: '100M'
    networks:
      - pterodactyl_network

  wings:
    # --- PERUBAHAN DI SINI ---
    # Menggunakan image tag yang lebih baru dan valid
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl_wings
    restart: always
    ports:
      - "8081:8080"
      - "2022:2022"
    depends_on:
      - panel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - ./data/wings:/etc/pterodactyl
      - ./data/servers:/var/lib/pterodactyl/volumes
    environment:
      WINGS_UID: 1000 # Pastikan ini UID pengguna non-root Anda
      WINGS_GID: 1000 # Pastikan ini GID pengguna non-root Anda
      WINGS_IP: 127.0.0.1
    networks:
      - pterodactyl_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pterodactyl_phpmyadmin
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - database
    environment:
      PMA_HOST: 'database'
      MYSQL_ROOT_PASSWORD: 'bgsgtg' # Gunakan password root yang sama
    networks:
      - pterodactyl_network

networks:
  pterodactyl_network:
    driver: bridge

volumes:
  data-mysql:
  data-panel:
  data-nginx:
  data-wings:
  data-servers:
